### ISSUE TITLE
Search only works for first 200 characters of each doc

### ISSUE THREAD

**Issue by jamespohalloran** [tinacms/tinacms.org#1044]
On tina.io, when I search for something like `useDocumentCreatorPlugin`, there are no results. ~~It seems that we're not generating/updating the algolia index anymore~~

**Comment by mittonface** [comment]
So it looks like this was done here https://github.com/tinacms/tinacms.org/pull/617

My best guess is that this was done so that we could neatly display the text and highlight the matching bits in the text. Definitely could be other reasons though. @spbyrne do you have any memory of this?

If that's the case we might be able to get away with an alternative way of doing this where we index the entire body, and then trim what algolia displays to us at search time.
