### ISSUE TITLE
Tina CMS needs to install tailwind in order to show UI properly

### ISSUE THREAD

**Issue by AntonWeigel** [tinacms/tinacms.org#1097]
**Problem:** I don't use tailwind and styled-components in my project, but Tiny CMS forces me to install and config this dependencies. What was not obviously from the docs.

I had some UI issues with Tina CMS panel. After investigation, I recognized, that html elements of the panel don't have css classes, which should come from tailwind. I was able to fix it with following steps:

- Install dependencies: tailwindcss
- Install devDependencies: postcss
- add new config file in root of the project: postcss.config.js
module.exports = {
  plugins: ['tailwindcss', 'autoprefixer'],
};
- add tailwind import to my css baseline: @tailwind utilities;

maybe that info can help somebody else.

**Comment by perkinsjr** [comment]
@AntonWeigel thanks for reaching out with this issue and guidance for others. This was actually a bug on our side and should be fixed with the latest version (0.59.0). We don't require you to have tailwind or style components. 

Sorry for any confusion and pain points you might have had. If you continue to run into the issue please re-open this issue and we can investigate futher.

**Comment by AntonWeigel** [comment]
@perkinsjr Thanks for your work 😊
