### ISSUE TITLE
"StackBlitz" or "CodeSandbox" environments for quick starter introduction

### ISSUE THREAD

**Issue by perkinsjr** [tinacms/tinacms.org#1113]
Find a potential way to use our quick starter intro using Stack Blitz

**Comment by jeffsee55** [comment]
We should snag the tina.new domain

**Comment by perkinsjr** [comment]
So far it seems that neither StackBlitz / Gitpod / CodeSandbox work directly out of the box. Further investigation will be required

**Comment by jamespohalloran** [comment]
It seems like the complexity is all around the local graphQL server I assume eh? 
Wondering if the readonly token's might unlock this, (or an internal sandbox project of some sort). Our hosted examples can hit our API instead of any local server. When the user saves, we could just show an alert that it's a "sandbox environment". 

Even if we didn't want to expose readonly tokens to all our users at this point, maybe this would be a good use case to build it as a hidden "beta" feature?
Thoughts @jeffsee55 ?

**Comment by jamespohalloran** [comment]
Also, if we went fully frontend with the examples, might be worth considering sandpack.
Really like their React docs example: https://beta.reactjs.org/learn

**Comment by kldavis4** [comment]
Another thought about this I had during office hours today and the deep dive around branching (and also extending on what JamesO suggests) was if we had the content database implemented in such a way that content-api could run with the git bridge un-configured, then we could in theory seed a site per user on demand from a starter into the content db, and provide some sandboxed access to it without any special authorization. In that state we'd be able to have a fully "working" sandbox example that didn't require any special auth

**Comment by jeffsee55** [comment]
@kldavis4 that makes sense to me, we kind of do this with the memory bridge in the tinacms.org dummy graphql docs https://github.com/tinacms/tinacms.org/blob/master/pages/api/graphiql.ts. We can probably take this much further with a DB that just never writes back to Github (since there's no account).

**Comment by jeffsee55** [comment]
This also gets back to where things left off on open authoring. We're basically saying that we're ok with the idea that users can land on a page, enter edit mode and start to make changes, upon hitting save - we ask them to login. Those would be unauthenticated hits to our DB, but we'll presumably be able to protect ourselves with rate limiting. 

We may also be able to take things further and allow them to save, refresh, and bounce around to other pages (even other "open" branches?) before they actually "commit" those changes. Currently the data store prefixes keys with something like `"<repo-owner>/<repo-name>/<ref-name>/..."`, we could just as easily do some random hash prefix, and then when they've created an account and Github repo we swap that out with the appropriate info.

**Comment by jeffsee55** [comment]
Moving forward you'll need to implement the Bridge and Store, hopefully that story gets cleaned up soon though. You can see how that's been done for something I did similar to this project here. I'll make a ticket to expose the following:
`Bridge` interface, `Store` interface, `sequential` utility

**Comment by jamespohalloran** [comment]
Closing now that we have the embedded playgrounds
